### ISSUE TITLE
Code instead of text in tooltip

### ISSUE THREAD

**Issue by einsteinsfool** [GBKS/exploremonero-i18n#6]
I know this is a repo only for translations but I figured there's no harm in reporting a bug on the website.

When you go to the [blocks page](https://www.exploremonero.com/blocks) and onMouseOver on the blue progressbar there's a code instead of text (or rather translation).
![screenshot_20180724_182549](https://user-images.githubusercontent.com/24587734/43153053-85ff1b2a-8f70-11e8-9f87-6c239d7e9585.png)

Happens both in Firefox 62 in safe mode (without extensions) and in Chromium 67 without extensions.

**Comment by GBKS** [comment]
Thanks for reporting, just fixed it.
